"""
Orchestrator - The master process that coordinates the AI Employee.

The orchestrator:
1. Watches the Needs_Action folder for new items
2. Triggers Claude Code to process pending items
3. Updates the Dashboard.md with current status
4. Manages the overall workflow

Usage:
    python orchestrator.py /path/to/vault
"""

import subprocess
import logging
import shutil
import json
from pathlib import Path
from datetime import datetime
from typing import List, Optional

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class Orchestrator:
    """
    Main orchestrator for the AI Employee.
    
    Coordinates between watchers, Claude Code, and the vault.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the orchestrator.
        
        Args:
            vault_path: Path to the Obsidian vault root
        """
        self.vault_path = Path(vault_path).resolve()
        self.logger = logging.getLogger('Orchestrator')
        
        # Folder paths
        self.inbox = self.vault_path / 'Inbox'
        self.needs_action = self.vault_path / 'Needs_Action'
        self.done = self.vault_path / 'Done'
        self.plans = self.vault_path / 'Plans'
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.rejected = self.vault_path / 'Rejected'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure all folders exist
        for folder in [self.inbox, self.needs_action, self.done, 
                       self.plans, self.pending_approval, self.approved,
                       self.rejected, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
        
        self.logger.info(f'Orchestrator initialized for vault: {self.vault_path}')
    
    def count_pending_items(self) -> dict:
        """Count items in each folder (all files, not just .md)."""
        return {
            'needs_action': len(list(self.needs_action.iterdir())),
            'plans': len(list(self.plans.iterdir())),
            'pending_approval': len(list(self.pending_approval.iterdir())),
            'approved': len(list(self.approved.iterdir())),
            'done_today': self._count_done_today(),
        }
    
    def _count_done_today(self) -> int:
        """Count items moved to Done today."""
        today = datetime.now().strftime('%Y%m%d')
        return len(list(self.done.glob(f'*{today}*')))
    
    def update_dashboard(self):
        """Update the Dashboard.md with current status."""
        counts = self.count_pending_items()
        timestamp = datetime.now().isoformat()
        
        # Read current dashboard
        if self.dashboard.exists():
            content = self.dashboard.read_text()
        else:
            content = '''---
last_updated: {timestamp}
status: active
---

# AI Employee Dashboard

## Quick Status

| Metric | Value |
|--------|-------|
| Pending Items | {pending} |
| In Progress | 0 |
| Awaiting Approval | {approval} |
| Completed Today | {done} |

## Bank Balance

> **Current Balance:** $0.00
> 
> **Last Updated:** Not yet synced

## Pending Messages

*No pending messages*

## Active Business Projects

*No active projects*

## Recent Activity

| Date | Action | Status |
|------|--------|--------|
| - | - | - |

## Quick Links

- [[Business_Goals]] - Q1/Q2 objectives
- [[Company_Handbook]] - Rules of engagement
- `/Needs_Action/` - Items requiring attention
- `/Pending_Approval/` - Awaiting your approval
- `/Done/` - Completed tasks

---
*Generated by AI Employee v0.1 (Bronze Tier)*
'''
        
        # Update the dashboard
        new_content = content.replace(
            'last_updated: {}'.format(
                content.split('last_updated: ')[1].split('\n')[0] if 'last_updated:' in content else '2026-02-25T00:00:00Z'
            ),
            f'last_updated: {timestamp}'
        )
        
        # Update counts if placeholders exist
        if '{pending}' in new_content:
            new_content = new_content.format(
                timestamp=timestamp,
                pending=counts['needs_action'],
                approval=counts['pending_approval'],
                done=counts['done_today']
            )
        
        self.dashboard.write_text(new_content)
        self.logger.info(f'Dashboard updated: {counts["needs_action"]} pending items')
    
    def get_pending_items(self) -> List[Path]:
        """Get list of pending .md files in Needs_Action."""
        return sorted(self.needs_action.glob('*.md'))
    
    def process_with_qwen(self, items: List[Path]) -> bool:
        """
        Process items using Qwen Code.
        
        For each item:
        1. Read the .meta.md file content
        2. Call Qwen Code to analyze and get routing recommendation (JSON)
        3. Move file to appropriate folder based on Qwen's decision
        
        Args:
            items: List of .meta.md files to process

        Returns:
            True if processing was successful
        """
        if not items:
            self.logger.info('No items to process')
            return True

        self.logger.info(f'Processing {len(items)} items with Qwen Code')
        
        processed_count = 0
        approval_count = 0
        done_count = 0

        for item in items:
            self.logger.info(f'Analyzing item: {item.name}')
            
            # Read the item content
            try:
                content = item.read_text(encoding='utf-8')
            except Exception as e:
                self.logger.error(f'Failed to read {item.name}: {e}')
                continue
            
            # Build prompt for Qwen Code analysis
            prompt = self._build_analysis_prompt(item, content)
            
            # Call Qwen Code to get routing recommendation
            recommendation = self._call_qwen_for_analysis(prompt)
            
            if recommendation:
                # Extract routing decision
                target_folder = recommendation.get('target_folder', 'needs_action')
                reason = recommendation.get('reason', 'No reason provided')
                requires_approval = recommendation.get('requires_approval', False)
                
                self.logger.info(f'Qwen recommendation: {target_folder} (Reason: {reason})')
                
                # Route to appropriate folder
                if requires_approval or target_folder == 'pending_approval':
                    self._move_item_to_folder(item, self.pending_approval)
                    approval_count += 1
                elif target_folder == 'done':
                    self._move_item_to_folder(item, self.done)
                    done_count += 1
                elif target_folder == 'plans':
                    self._move_item_to_folder(item, self.plans)
                else:
                    # Keep in needs_action but log the analysis
                    self._log_analysis_result(item, recommendation)
                
                processed_count += 1
            else:
                # Qwen failed to analyze, keep in needs_action
                self.logger.warning(f'Failed to get recommendation for {item.name}')
                self._log_analysis_result(item, {'error': 'Qwen analysis failed'})
        
        self.logger.info(f'Processed {processed_count} items: {done_count} to Done, {approval_count} to Pending Approval')
        return True
    
    def _build_analysis_prompt(self, item: Path, content: str) -> str:
        """Build the prompt for Qwen Code analysis."""
        return f'''You are an AI Employee workflow assistant. Analyze this action item and determine where it should be routed.

File: {item.name}

Content:
{content}

---

Company Handbook Rules:
- All payments require human approval (route to pending_approval)
- Emails to new contacts require approval (route to pending_approval)
- Transactions over $500 require approval (route to pending_approval)
- Simple informational files can go directly to done
- Files that need multi-step planning go to plans
- Urgent items stay in needs_action with high priority

---

Folder meanings:
- done: Task is complete or requires no action (informational, auto-processable)
- pending_approval: Requires human approval before proceeding (payments, sensitive actions)
- plans: Needs multi-step planning or complex execution
- needs_action: Needs more work, clarification, or is already being handled

---

Return ONLY a JSON object with this exact structure:
{{
    "target_folder": "done" | "pending_approval" | "plans" | "needs_action",
    "requires_approval": true | false,
    "reason": "Brief explanation of the routing decision",
    "priority": "high" | "medium" | "low",
    "action_summary": "One line summary of what this item is about"
}}

Do not include any text before or after the JSON.'''
    
    def _call_qwen_for_analysis(self, prompt: str) -> dict:
        """
        Call Qwen Code to analyze content and return JSON recommendation.

        Uses 'qwen -p' to pass the prompt directly with explicit system message for JSON output.
        """
        import json
        import re

        try:
            # Use shell=True on Windows to support .cmd files
            import platform
            use_shell = platform.system() == 'Windows'

            self.logger.info('Calling Qwen Code for analysis...')

            # Build a system message that enforces JSON-only output
            system_message = '''You are a JSON API endpoint. Your ONLY output must be valid JSON.

CRITICAL INSTRUCTIONS:
- Do NOT write any text before or after the JSON
- Do NOT explain, summarize, or add commentary
- Do NOT use markdown code blocks (no ```)
- Output ONLY the raw JSON object
- If you cannot analyze the content, return: {"error": "Unable to analyze"}

This is a machine-to-machine communication. Any non-JSON output will break the system.'''

            # Combine system message with user prompt
            full_prompt = f'''{system_message}

--- BEGIN USER INPUT ---

{prompt}

--- END USER INPUT ---

Remember: Output ONLY JSON, nothing else.'''

            # Run Qwen Code with the analysis prompt
            result = subprocess.run(
                ['qwen', '-p', full_prompt],
                capture_output=True,
                text=True,
                timeout=120,  # 2 minutes for analysis
                shell=use_shell
            )

            if result.returncode != 0:
                self.logger.error(f'Qwen Code error (returncode {result.returncode}): {result.stderr[:200]}')
                return None

            output = result.stdout.strip()
            self.logger.info(f'Qwen Code response received ({len(output)} chars)')

            # Extract JSON from response (may have markdown code blocks)
            # Look for {...} pattern
            json_match = re.search(r'\{[\s\S]*\}', output)
            if json_match:
                json_str = json_match.group(0)
                # Clean up any markdown code block markers
                json_str = json_str.replace('```json', '').replace('```', '').strip()

                try:
                    recommendation = json.loads(json_str)

                    # Validate required fields
                    required_fields = ['target_folder', 'requires_approval', 'reason']
                    if all(field in recommendation for field in required_fields):
                        # Validate target_folder value
                        valid_folders = ['done', 'pending_approval', 'plans', 'needs_action']
                        if recommendation.get('target_folder') in valid_folders:
                            self.logger.info(f'Valid recommendation: {recommendation.get("target_folder")}')
                            return recommendation
                        else:
                            self.logger.warning(f'Invalid target_folder: {recommendation.get("target_folder")}')
                            return None
                    else:
                        self.logger.warning(f'Missing required fields: {recommendation}')
                        return None

                except json.JSONDecodeError as parse_error:
                    self.logger.error(f'JSON parse error: {parse_error}')
                    self.logger.debug(f'Raw JSON string: {json_str[:500]}')
                    return None
            else:
                self.logger.warning(f'No JSON found in response: {output[:200]}...')
                return None

        except subprocess.TimeoutExpired:
            self.logger.error('Qwen Code analysis timed out (120s)')
            return None
        except Exception as e:
            self.logger.error(f'Error calling Qwen Code: {e}')
            return None
    
    def _move_item_to_folder(self, item: Path, target_folder: Path):
        """
        Move an item and its associated data file to a target folder.
        
        Handles both .meta.md files and their associated data files.
        """
        # Extract base name (e.g., FILE_test.txt.meta.md -> FILE_test.txt)
        base_name = item.stem  # Removes .md
        if base_name.endswith('.meta'):
            base_name = base_name[:-5]  # Removes .meta
        
        # Find associated data file in same folder
        data_file = item.parent / base_name
        
        # Move the meta file
        dest_meta = target_folder / item.name
        try:
            shutil.move(str(item), str(dest_meta))
            self.logger.info(f'Moved {item.name} to {target_folder.name}/')
        except Exception as e:
            self.logger.error(f'Failed to move {item.name}: {e}')
            return
        
        # Move associated data file if exists
        if data_file.exists():
            data_dest = target_folder / data_file.name
            try:
                shutil.move(str(data_file), str(data_dest))
                self.logger.info(f'Moved {data_file.name} to {target_folder.name}/')
            except Exception as e:
                self.logger.error(f'Failed to move {data_file.name}: {e}')
    
    def _log_analysis_result(self, item: Path, recommendation: dict):
        """Log the analysis result for an item that stays in needs_action."""
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'item': item.name,
            'recommendation': recommendation
        }
        
        # Append to daily log
        log_file = self.logs / f'{datetime.now().strftime("%Y-%m-%d")}.jsonl'
        
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(json.dumps(log_entry) + '\n')
        
        self.logger.debug(f'Logged analysis for {item.name}')
    
    def _create_plan_for_items(self, items: List[Path], prompt: str):
        """Create a plan file for items to be processed."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_file = self.plans / f'PLAN_batch_{timestamp}.md'
        
        items_section = '\n'.join([
            f'- [ ] Process `{item.name}`' for item in items
        ])
        
        content = f'''---
created: {datetime.now().isoformat()}
status: pending
type: batch_plan
items: {len(items)}
---

# Batch Processing Plan

## Items to Process

{items_section}

## Instructions for Claude Code

Run the following prompt:

```
{prompt}
```

## Manual Processing Steps

If Claude Code is not available:

1. Read each file in `/Needs_Action/`
2. Determine required action based on [[Company_Handbook]]
3. For approvals: Create file in `/Pending_Approval/`
4. For simple tasks: Process and move to `/Done/`
5. Update [[Dashboard]] with results

## Status

- [ ] All items processed
- [ ] Dashboard updated
- [ ] Files moved to appropriate folders

---
*Created by Orchestrator v0.1*
'''
        plan_file.write_text(content)
        self.logger.info(f'Created plan file: {plan_file.name}')
    
    def _create_manual_processing_note(self, items: List[Path]):
        """Create a note for manual processing when Claude is unavailable."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        note_file = self.plans / f'MANUAL_PROCESS_{timestamp}.md'
        
        items_list = '\n'.join([
            f'- `{item.name}`' for item in items
        ])
        
        content = f'''---
created: {datetime.now().isoformat()}
status: requires_manual_attention
type: manual_processing_note
---

# Manual Processing Required

Claude Code is not available. Please process these items manually:

## Items Waiting

{items_list}

## Next Steps

1. Install Claude Code: `npm install -g @anthropic/claude-code`
2. Or process these items manually:
   - Read each file in `/Needs_Action/`
   - Take appropriate action
   - Move to `/Done/` when complete

## Quick Start with Claude Code

```bash
# Install
npm install -g @anthropic/claude-code

# Verify
claude --version

# Process items
claude "Process all files in Needs_Action folder"
```

---
*Created by Orchestrator v0.1*
'''
        note_file.write_text(content)
        self.logger.warning(f'Created manual processing note: {note_file.name}')
    
    def check_approved_actions(self) -> List[Path]:
        """Check for approved actions ready to execute."""
        return list(self.approved.glob('*.md'))
    
    def execute_approved_action(self, action_file: Path) -> bool:
        """
        Execute an approved action.
        
        For Bronze tier, this just logs the action and moves to Done.
        Higher tiers will integrate with MCP servers.
        """
        self.logger.info(f'Executing approved action: {action_file.name}')
        
        # For Bronze tier: just move to Done
        dest = self.done / action_file.name
        shutil.move(str(action_file), str(dest))
        
        self.logger.info(f'Action completed: {dest}')
        return True
    
    def run_cycle(self):
        """Run one complete orchestration cycle."""
        self.logger.info('Starting orchestration cycle')
        
        # Update dashboard
        self.update_dashboard()

        # Get pending items
        pending = self.get_pending_items()

        if pending:
            # Process with Qwen Code
            self.process_with_qwen(pending)

        # Check for approved actions
        approved = self.check_approved_actions()
        for action in approved:
            self.execute_approved_action(action)

        # Final dashboard update
        self.update_dashboard()

        self.logger.info('Orchestration cycle complete')

    def move_to_done(self, meta_file: Path):
        """
        Move a meta file and its associated data file to Done.
        
        Args:
            meta_file: The .meta.md file to move
        """
        # Extract base name (e.g., FILE_test.txt.meta.md -> FILE_test.txt)
        base_name = meta_file.stem  # Removes .md
        if base_name.endswith('.meta'):
            base_name = base_name[:-5]  # Removes .meta
        
        # Find associated files
        data_file = self.needs_action / base_name
        
        # Move meta file
        dest_meta = self.done / meta_file.name
        shutil.move(str(meta_file), str(dest_meta))
        self.logger.info(f'Moved {meta_file.name} to Done')
        
        # Move data file if exists
        if data_file.exists():
            dest_data = self.done / data_file.name
            shutil.move(str(data_file), str(dest_data))
            self.logger.info(f'Moved {data_file.name} to Done')
    
    def run_continuous(self, cycle_interval: int = 60):
        """
        Run the orchestrator continuously.
        
        Args:
            cycle_interval: Seconds between cycles
        """
        self.logger.info(f'Starting continuous orchestration (interval: {cycle_interval}s)')
        
        import time
        
        while True:
            try:
                self.run_cycle()
            except Exception as e:
                self.logger.error(f'Error in orchestration cycle: {e}')
            
            time.sleep(cycle_interval)


def main():
    """Main entry point."""
    import sys
    
    # Get vault path from command line or use current directory
    if len(sys.argv) > 1:
        vault_path = sys.argv[1]
    else:
        vault_path = '.'
    
    vault_path = Path(vault_path).resolve()
    
    if not vault_path.exists():
        print(f'Error: Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    print(f'AI Employee - Orchestrator v0.1 (Bronze Tier)')
    print(f'Vault: {vault_path}')
    print()
    print('Commands:')
    print('  run       - Run one orchestration cycle')
    print('  watch     - Run continuously (default)')
    print('  status    - Show current status')
    print()
    
    orchestrator = Orchestrator(str(vault_path))
    
    command = sys.argv[2] if len(sys.argv) > 2 else 'watch'
    
    if command == 'run':
        orchestrator.run_cycle()
    elif command == 'status':
        counts = orchestrator.count_pending_items()
        print(f'Pending items: {counts["needs_action"]}')
        print(f'Pending approval: {counts["pending_approval"]}')
        print(f'Completed today: {counts["done_today"]}')
    else:  # watch
        print('Watching for changes. Press Ctrl+C to stop.')
        print()
        orchestrator.run_continuous()


if __name__ == '__main__':
    main()
